### ISSUE TITLE
undefined method 'bytesize'

### ISSUE THREAD

**Issue by wdawson4** [spikebrehm/sprockets-node-example#1]
Spike, 
Thanks for your demonstration on monday. I am having trouble running the example you posted here. Any recommendations on how to solve?
# Request to localhost:3000

``` erb
Started GET "/" for ::1 at 2015-02-09 15:57:41 -0800
Processing by HomeController#index as HTML
  Rendered home/index.html.erb within layouts/application (9.7ms)
Completed 500 Internal Server Error in 15ms


ActionView::Template::Error (undefined method `bytesize' for nil:NilClass):
    15:   <p>Part of <a href="http://todomvc.com">TodoMVC</a></p>
    16: </footer>
    17:
    18: <%= javascript_include_tag 'globals/manifest.js' %>
  app/views/home/index.html.erb:18:in `_app_views_home_index_html_erb___1255414196832334667_2237921020'

```
# Request to localhost:3000/commonjs

``` erb
Started GET "/commonjs" for ::1 at 2015-02-09 15:57:49 -0800
Processing by HomeController#commonjs as HTML
  Rendered home/commonjs.html.erb within layouts/application (10.9ms)
Completed 500 Internal Server Error in 46ms

ActionView::Template::Error (undefined method `bytesize' for nil:NilClass):
    3: <head>
    4:   <title>Sprockets Node Example</title>
    5:   <%= stylesheet_link_tag    'application', media: 'all' %>
    6:   <%= javascript_include_tag 'application' %>
    7:   <%= csrf_meta_tags %>
    8: </head>
    9: <body>
  app/views/layouts/application.html.erb:6:in `_app_views_layouts_application_html_erb___3950431967555712526_2237899980'


```

**Comment by wdawson4** [comment]
@spikebrehm 

#### the error is being thrown from Rack::Utils.bytesize(source) in ProcessedAsset

rack (1.6.0) lib/rack/utils.rb:361:in 'bytesize'
sprockets (2.12.3) lib/sprockets/processed_asset.rb:13:in 'initialize'
 Extracted source (around line #13) from processed_asset.rb:

``` ruby
context = environment.context_class.new(environment, logical_path, pathname)
@source = context.evaluate(pathname)
@length = Rack::Utils.bytesize(source)
@digest = environment.digest.update(source).hexdigest
build_required_assets(environment, context)
```

**Comment by spikebrehm** [comment]
Weird, I don't know what to tell you.  Which version of Ruby are you using?

**Comment by wdawson4** [comment]
Ruby 2.1.0

**Comment by Granze** [comment]
I had the same problem. You can solve it by changing the `evaluate` method in `browserify_template.rb`

``` ruby
def evaluate(scope, locals, &block)
    if self.class.is_bundle?(scope.pathname)
      # Process file's dependencies, using Browserify.
      deps = bundler('deps', scope.pathname)

      deps.lines.reject do |path|
        scope.resolve(path.strip) == scope.pathname
      end.each do |path|
        scope.depend_on(path.strip)
      end

      # Transform the file with Browserify.
      @output = bundler('bundle', scope.pathname)
    end

    @output || ''
  end
```
